package com.faceswaplocal.app.inference

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlinx.coroutines.runBlocking
import org.json.JSONObject
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Stage E1 parity core. Feeds the committed, byte-identical ffhq_512 crop
 * (`pair_01_enhancer_input_512.png`) to the Android GFPGAN and BiSeNet sessions and
 * compares against the desktop FaceFusion 3.7.1 reference generated by
 * `docs/parity/make_enhancer_reference.py`. No swap runs here, so the input is
 * deterministic and iteration is fast.
 *
 * Gate before any orchestration:
 *  - GFPGAN raw output SSIM to desktop >= 0.95 (§11.4);
 *  - BiSeNet region mask IoU to desktop >= 0.95 (binary region set), plus class agreement.
 */
@RunWith(AndroidJUnit4::class)
class FaceEnhancerParityInstrumentedTest {
    private val context = ApplicationProvider.getApplicationContext<Context>()
    private val assets = InstrumentationRegistry.getInstrumentation().context.assets

    @Test
    fun gfpganAndParserMatchDesktopOnFixedCrop() {
        runBlocking {
            val store = ModelStore(context)
            store.refreshStatuses()
            val enhancer = OnnxFaceEnhancerPipeline(store)
            val crop = decodeBitmap("inputs/pair_01_enhancer_input_512.png")
            try {
                // GFPGAN parity.
                val (actualRaw, enhancerBackend) = enhancer.enhanceRawOutput(crop, RequestedInferenceBackend.CPU_ONLY)
                val referenceRaw = readFloatAsset("reference/facefusion-3.7.1/enhancer/pair_01/gfpgan_output_f32le.bin")
                val gfpganSsim = structuralSimilarity(
                    normalizeToUnit(actualRaw),
                    normalizeToUnit(referenceRaw),
                    OnnxFaceEnhancerPipeline.ENHANCER_SIZE,
                    OnnxFaceEnhancerPipeline.ENHANCER_SIZE,
                )

                // BiSeNet parser parity.
                val (actualClasses, parserBackend) = enhancer.parseArgmax(crop, RequestedInferenceBackend.CPU_ONLY)
                val referenceClasses = readByteAsset("reference/facefusion-3.7.1/enhancer/pair_01/region_argmax_512.bin")
                val regionIou = binaryRegionIou(actualClasses, referenceClasses)
                val classAgreement = classAgreement(actualClasses, referenceClasses)

                val metrics = JSONObject()
                    .put("gfpgan_ssim", gfpganSsim)
                    .put("region_iou", regionIou)
                    .put("class_agreement", classAgreement)
                    .put("enhancer_backend", enhancerBackend.name)
                    .put("parser_backend", parserBackend.name)
                File(context.filesDir, "stage-e1-parity").apply { mkdirs() }
                    .let { dir -> File(dir, "enhancer_parity_results.json").writeText(metrics.toString(2)) }

                assertTrue("GFPGAN SSIM $gfpganSsim must be >= 0.95", gfpganSsim >= 0.95)
                assertTrue("Region mask IoU $regionIou must be >= 0.95", regionIou >= 0.95)
                assertTrue("Class agreement $classAgreement must be >= 0.95", classAgreement >= 0.95)
            } finally {
                crop.recycle()
            }
        }
    }

    private fun normalizeToUnit(chwMinusOneToOne: FloatArray): FloatArray =
        FloatArray(chwMinusOneToOne.size) { index -> (chwMinusOneToOne[index].coerceIn(-1f, 1f) + 1f) / 2f }

    private fun binaryRegionIou(actual: IntArray, reference: IntArray): Double {
        val regions = OnnxFaceEnhancerPipeline.REGION_CLASS_IDS.toHashSet()
        var intersection = 0
        var union = 0
        for (index in actual.indices) {
            val a = actual[index] in regions
            val b = reference[index] in regions
            if (a || b) union++
            if (a && b) intersection++
        }
        return if (union == 0) 1.0 else intersection.toDouble() / union
    }

    private fun classAgreement(actual: IntArray, reference: IntArray): Double {
        var same = 0
        for (index in actual.indices) if (actual[index] == reference[index]) same++
        return same.toDouble() / actual.size
    }

    private fun decodeBitmap(path: String): Bitmap = assets.open(path).use { stream ->
        requireNotNull(BitmapFactory.decodeStream(stream)) { "Cannot decode parity asset $path" }
            .copy(Bitmap.Config.ARGB_8888, false)
    }

    private fun readFloatAsset(path: String): FloatArray = assets.open(path).use { input ->
        val bytes = input.readBytes()
        require(bytes.size % Float.SIZE_BYTES == 0)
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer()
        FloatArray(buffer.remaining()).also(buffer::get)
    }

    private fun readByteAsset(path: String): IntArray = assets.open(path).use { input ->
        input.readBytes().map { it.toInt() and 0xff }.toIntArray()
    }

    /** Skimage-compatible 7x7 uniform-window SSIM, averaged over RGB channels. */
    private fun structuralSimilarity(actual: FloatArray, expected: FloatArray, width: Int, height: Int): Double {
        require(actual.size == expected.size)
        require(3 * width * height == actual.size)
        val radius = 3
        val count = 49
        val covarianceScale = count.toDouble() / (count - 1).toDouble()
        val c1 = 0.01 * 0.01
        val c2 = 0.03 * 0.03
        val planeSize = width * height
        var total = 0.0
        var windows = 0
        for (channel in 0 until 3) {
            val planeOffset = channel * planeSize
            for (centerY in radius until height - radius) {
                for (centerX in radius until width - radius) {
                    var sumActual = 0.0
                    var sumExpected = 0.0
                    var sumActualSquared = 0.0
                    var sumExpectedSquared = 0.0
                    var sumProduct = 0.0
                    for (y in centerY - radius..centerY + radius) {
                        for (x in centerX - radius..centerX + radius) {
                            val index = planeOffset + y * width + x
                            val a = actual[index].toDouble()
                            val e = expected[index].toDouble()
                            sumActual += a
                            sumExpected += e
                            sumActualSquared += a * a
                            sumExpectedSquared += e * e
                            sumProduct += a * e
                        }
                    }
                    val meanActual = sumActual / count
                    val meanExpected = sumExpected / count
                    val varianceActual = (sumActualSquared / count - meanActual * meanActual) * covarianceScale
                    val varianceExpected = (sumExpectedSquared / count - meanExpected * meanExpected) * covarianceScale
                    val covariance = (sumProduct / count - meanActual * meanExpected) * covarianceScale
                    val numerator = (2 * meanActual * meanExpected + c1) * (2 * covariance + c2)
                    val denominator =
                        (meanActual * meanActual + meanExpected * meanExpected + c1) *
                            (varianceActual + varianceExpected + c2)
                    total += numerator / denominator
                    windows++
                }
            }
        }
        return total / windows
    }
}
